version: "3.6"
services:
    proxy_web:
        image: haproxy:latest
        container_name: contenedor_proxy_web
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.4
        ports:
            - "8443:8443"
            - "7777:7777"
        links:
            - web1
            - web2
        volumes:
            - ./proxyWeb/configuracion/:/usr/local/etc/haproxy/
    proxy_sinterno:
        image: haproxy:latest
        container_name: contenedor_proxy_sinterno
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.3
        ports:
            - "7000:7000"
            - "9999:9999"
        links:
            - servicio_interno1
            - servicio_interno2
        volumes:
            - ./proxyServicioInterno/configuracion/:/usr/local/etc/haproxy/

    web1:
        build: ./Bookteca/.
        container_name: contenedor_web1
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.7
        links:
            - base_datos_bookteca
            - proxy_sinterno
        environment:
            - SPRING.DATASOURCE.URL=jdbc:mysql://172.19.0.9/bookteca?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - SPRING.DATASOURCE.PASSWORD=bookteca

    web2:
        build: ./Bookteca/.
        container_name: contenedor_web2
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.5
        links:
            - base_datos_bookteca
            - proxy_sinterno
        environment:
            - SPRING.DATASOURCE.URL=jdbc:mysql://172.19.0.9/bookteca?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - SPRING.DATASOURCE.PASSWORD=bookteca

    base_datos_bookteca:
        image: mysql
        container_name: contenedor_bd_bookteca
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.9
        security_opt:
            - seccomp=unconfined
        volumes:
            - ./mysql/:/var/lib/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=bookteca
            - MYSQL_DATABASE=bookteca
            - MYSQL_USER=root
            - MYSQL_PASSWORD=bookteca

    servicio_interno1:
        build: ./ServicioInterno/.
        container_name: contenedor_sinterno1
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.6
        links:
            - base_datos_bookteca
        environment:
            - SPRING.DATASOURCE.URL=jdbc:mysql://172.19.0.9/bookteca?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - SPRING.DATASOURCE.PASSWORD=bookteca

    servicio_interno2:
        build: ./ServicioInterno/.
        container_name: contenedor_sinterno2
        networks:
            red_bookteca:
                ipv4_address: 172.19.0.8
        links:
            - base_datos_bookteca
        environment:
            - SPRING.DATASOURCE.URL=jdbc:mysql://172.19.0.9/bookteca?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - SPRING.DATASOURCE.PASSWORD=bookteca

networks:
    red_bookteca:
        external: true
        ipam:
            driver: default
            config:
                - subnet: "172.19.0.0/16"

